# Generated by Django 3.1.3 on 2021-06-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_mlalgorithmstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlalgorithm',
            old_name='descirption',
            new_name='description',
        ),
    ]
